### ISSUE TITLE
Update ORCID in all Github R packages 

### ISSUE THREAD

**Issue by mrustl** [KWB-R/kwb.orcid#1]
|repo                 |author                                                                                           |orcid               |
|:--------------------|:------------------------------------------------------------------------------------------------|:-------------------|
|KWB-R/aquanes.report |[1] "Michael Rustler <michael.rustler@kompetenz-wasser.de> [aut, cre] (0000-0003-0647-7726)"     |0000-0003-0647-7726 |
|KWB-R/kwb.base       |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre] (0000-0001-9134-2871)"   |0000-0001-9134-2871 |
|KWB-R/kwb.code       |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre] (0000-0001-9134-2871)"   |0000-0001-9134-2871 |
|KWB-R/kwb.datetime   |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre]"                         |NA                  |
|KWB-R/kwb.db         |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre]"                         |NA                  |
|KWB-R/kwb.default    |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre]"                         |NA                  |
|KWB-R/kwb.demeau     |[1] "Michael Rustler <michael.rustler@kompetenz-wasser.de> [aut, cre] (0000-0003-0647-7726)"     |0000-0003-0647-7726 |
|KWB-R/kwb.dwa.m150   |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre]"                         |NA                  |
|KWB-R/kwb.en13508.2  |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre]"                         |NA                  |
|KWB-R/kwb.event      |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre]"                         |NA                  |
|KWB-R/kwb.fakin      |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre] (0000-0001-9134-2871)"   |0000-0001-9134-2871 |
|KWB-R/kwb.hantush    |[1] "Michael Rustler <michael.rustler@kompetenz-wasser.de> [aut, cre] (0000-0003-0647-7726)"     |0000-0003-0647-7726 |
|KWB-R/kwb.logger     |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre]"                         |NA                  |
|KWB-R/kwb.monitoring |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre] (0000-0001-9134-2871)"   |0000-0001-9134-2871 |
|KWB-R/kwb.orcid      |[1] "Michael Rustler <michael.rustler@kompetenz-wasser.de> [aut, cre] (0000-0003-0647-7726)"     |0000-0003-0647-7726 |
|KWB-R/kwb.pkgbuild   |[1] "Michael Rustler <michael.rustler@kompetenz-wasser.de> [aut, cre] (0000-0003-0647-7726)"     |0000-0003-0647-7726 |
|KWB-R/kwb.pkgstatus  |[1] "Michael Rustler <michael.rustler@kompetenz-wasser.de> [aut, cre] (0000-0003-0647-7726)"     |0000-0003-0647-7726 |
|KWB-R/kwb.plot       |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre]"                         |NA                  |
|KWB-R/kwb.qmra       |[1] "Michael Rustler <michael.rustler@kompetenz-wasser.de> [aut, cre] (0000-0003-0647-7726)"     |0000-0003-0647-7726 |
|KWB-R/kwb.resilience |[1] "Andreas Matzinger <andreas.matzinger@kompetenz-wasser.de> [aut, cre] (0000-0001-5483-4594)" |0000-0001-5483-4594 |
|KWB-R/kwb.test       |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre]"                         |NA                  |
|KWB-R/kwb.umberto    |[1] "Michael Rustler <michael.rustler@kompetenz-wasser.de> [aut, cre] (0000-0003-0647-7726)"     |0000-0003-0647-7726 |
|KWB-R/kwb.utils      |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre] (0000-0001-9134-2871)"   |0000-0001-9134-2871 |
|KWB-R/kwb.vs2dh      |[1] "Michael Rustler <michael.rustler@kompetenz-wasser.de> [aut, cre] (0000-0003-0647-7726)"     |0000-0003-0647-7726 |
|KWB-R/kwb.wtaq       |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre]" 

Table created with the following R code: 
```
gh_repos <- kwb.pkgstatus::get_github_repos()

non_r_packages = c("kwb-r.github.io",
                   "fakin.blog", "fakin.doc", "HydroServerLite", "GeoSalz")

rpkgs <- gh_repos$full_name[!gh_repos$name %in% non_r_packages]

desc <- try(
  lapply(rpkgs, 
         function(x) {
  repo_url <- sprintf("https://raw.githubusercontent.com/%s/master/DESCRIPTION", x)
  tmpfile <- tempfile()
  download.file(url = repo_url, destfile = tmpfile, mode = "wb")
  desc <- desc::desc(file = tmpfile)
  
  authors_desc <- capture.output(desc$get_authors())
  index <- grep(pattern = "aut|cred", authors_desc)
  authors <- authors_desc[index]
  orcid_pattern <- "[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}"
  orcid <- stringr::str_extract(authors[index],pattern = orcid_pattern)
  data.frame(repo = x, 
                           author = authors, orcid = orcid,
                           stringsAsFactors = FALSE)
    }))

desc_list <- data.table::rbindlist(desc)

knitr::kable(desc_list)
```

**Comment by hsonne** [comment]
Great overview, thanks Michael!
Great job to be done, I like stupid things to do...
And, finally, done!
Please check again!

**Comment by mrustl** [comment]
|repo                 |author                                                                                                                |orcid               |
|:--------------------|:---------------------------------------------------------------------------------------------------------------------|:-------------------|
|KWB-R/aquanes.report |[1] "Michael Rustler <michael.rustler@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0003-0647-7726>)"      |0000-0003-0647-7726 |
|KWB-R/kwb.base       |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0001-9134-2871>)"    |0000-0001-9134-2871 |
|KWB-R/kwb.code       |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0001-9134-2871>)"    |0000-0001-9134-2871 |
|KWB-R/kwb.datetime   |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0001-9134-2871>)"    |0000-0001-9134-2871 |
|KWB-R/kwb.db         |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0001-9134-2871>)"    |0000-0001-9134-2871 |
|KWB-R/kwb.default    |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0001-9134-2871>)"    |0000-0001-9134-2871 |
|KWB-R/kwb.demeau     |[1] "Michael Rustler <michael.rustler@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0003-0647-7726>)"      |0000-0003-0647-7726 |
|KWB-R/kwb.dwa.m150   |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0001-9134-2871>)"    |0000-0001-9134-2871 |
|KWB-R/kwb.en13508.2  |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0001-9134-2871>)"    |0000-0001-9134-2871 |
|KWB-R/kwb.event      |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0001-9134-2871>)"    |0000-0001-9134-2871 |
|KWB-R/kwb.fakin      |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0001-9134-2871>)"    |0000-0001-9134-2871 |
|KWB-R/kwb.hantush    |[1] "Michael Rustler <michael.rustler@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0003-0647-7726>)"      |0000-0003-0647-7726 |
|KWB-R/kwb.logger     |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0001-9134-2871>)"    |0000-0001-9134-2871 |
|KWB-R/kwb.monitoring |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0001-9134-2871>)"    |0000-0001-9134-2871 |
|KWB-R/kwb.orcid      |[1] "Michael Rustler <michael.rustler@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0003-0647-7726>)"      |0000-0003-0647-7726 |
|KWB-R/kwb.pkgbuild   |[1] "Michael Rustler <michael.rustler@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0003-0647-7726>)"      |0000-0003-0647-7726 |
|KWB-R/kwb.pkgstatus  |[1] "Michael Rustler <michael.rustler@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0003-0647-7726>)"      |0000-0003-0647-7726 |
|KWB-R/kwb.plot       |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0001-9134-2871>)"    |0000-0001-9134-2871 |
|KWB-R/kwb.qmra       |[1] "Michael Rustler <michael.rustler@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0003-0647-7726>)"      |0000-0003-0647-7726 |
|KWB-R/kwb.resilience |[1] "Andreas Matzinger <andreas.matzinger@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0001-5483-4594>)"  |0000-0001-5483-4594 |
|KWB-R/kwb.test       |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre]" "Kompetenzzentrum Wasser Berlin gGmbH [cph]" |NA                  |
|KWB-R/kwb.umberto    |[1] "Michael Rustler <michael.rustler@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0003-0647-7726>)"      |0000-0003-0647-7726 |
|KWB-R/kwb.utils      |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0001-9134-2871>)"    |0000-0001-9134-2871 |
|KWB-R/kwb.vs2dh      |[1] "Michael Rustler <michael.rustler@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0003-0647-7726>)"      |0000-0003-0647-7726 |
|KWB-R/kwb.wtaq       |[1] "Hauke Sonnenberg <hauke.sonnenberg@kompetenz-wasser.de> [aut, cre] (<https://orcid.org/0000-0001-9134-2871>)"    |0000-0001-9134-2871 |

**Comment by mrustl** [comment]
Almost done ;-)

**Comment by hsonne** [comment]
kwb.test updated, done!
